
ruby_image: &ruby_image
  circleci/ruby:2.4.4-node-browsers

bundle_cache_key: &bundle_cache_key
  auto-bundleupdate-{{ checksum "Gemfile.lock" }}

version: 2
jobs:
  ci-bundle-update:
    docker:
      - image: *ruby_image

    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache_key

      - run:
          name: circleci-bundle-update-pr
          command: |
            gem update bundler --no-document
            gem install circleci-bundle-update-pr
            bundle config --local path vendor/bundle
            circleci-bundle-update-pr
workflows:
  version: 2
  ci-bundle-update:
    triggers:
      - schedule:
          cron: "0 * * * 1-5"  # debug
          # cron: "0 22 * * 0"  # 日曜日 UTC 22:00 に実行
          filters:
            branches:
              only:
                - develop # developだけで実行
    jobs:
      - ci-bundle-update